### ISSUE TITLE
Publish changes on NPM

### ISSUE THREAD

**Issue by seballot** [seballot/ep_tables2#29]
Hi @quenenni 
I would like to publish my changes on Npm, but on don't have authorization to publish on ep_tables2.
Is there a way for you to give me access rights for ep_tables2 package? 
I could change the name to ep_tables3, but well, that is not really convenient !

Thanks

**Comment by quenenni** [comment]
Hello,

Ok, I just succeeded to find my login / passwd for the Npm website.. pfewww.. It was a long time since I used it.

The only package in my npm account is the ep_tables2.
So I don't care to keep it or not.
The best is, I guess, to change the email address associated with the account and put yours.
After that, you should be able to use the 'I lost my passwd' feature to create your own.

Ok with that?

**Comment by quenenni** [comment]
Can you send me pa private msg with the email address you want me to use (if you agree with the plan).

**Comment by seballot** [comment]
Hi ! thanks for you quick reply, I just found that : https://docs.npmjs.com/cli/owner

My user on npm is also "seballot", could you try this way? it seems better :)

**Comment by quenenni** [comment]
Hello,

Not sure if you'll receive this reply, so a a small test first.
Here is my mail address for further discussions: kenny@bruxxel.org

Kenny
